# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Vishakh Hegde
tagline:          Neural Network Trainer
description:      Neural Network Trainer
url:              https://vishakhhegde.github.io
baseurl:
paginate:         5
name:             Vishakh Hegde

twitter_name:     vishakhhegde
github_name:      vishakhhegde
linkedin_name:    vishakhhegde
